
import { Routes } from '@angular/router';

export const adminRoute: Routes = [
  { path: 'IMS/ItemGroupMaster/Index', loadComponent: () => import('../../components/ItemGroupMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'IMS/UOMMaster/Index', loadComponent: () => import('../../components/UOM-Master/index/index.component').then((m) => m.IndexComponent) },

  { path: 'manufacturer-master/index', loadComponent: () => import('../../components/Manufacturer-Master/index/index.component').then((m) => m.IndexComponent) },
  // { path: 'manufacturer-master/create', loadComponent: () => import('../../components/Manufacturer-Master/create/create.component').then((m) => m.CreateComponent) },
  // { path: 'manufacturer-master/edit/:ManufacturerID', loadComponent: () => import('../../components/Manufacturer-Master/create/create.component').then((m) => m.CreateComponent) },

  { path: 'item-group/index', loadComponent: () => import('../../components/Item-Group/index/index.component').then((m) => m.IndexComponent) },

  { path: 'IMS/CategoryMaster/Index', loadComponent: () => import('../../components/ims-category-master/index/index.component').then((m) => m.IndexComponent) },
  { path: 'IMS/CategoryMaster/Create', loadComponent: () => import('../../components/ims-category-master/create/create.component').then((m) => m.CreateComponent) },
  { path: 'IMS/CategoryMaster/Edit/:id', loadComponent: () => import('../../components/ims-category-master/create/create.component').then((m) => m.CreateComponent) },

  // { path: 'Admin/ProductMaster/Index', component: Index_ProductMasterComponent, pathMatch: 'full' },
  // { path: 'Admin/ProductMaster/Create', component: Create_ProductMasterComponent, pathMatch: 'full' },
  // { path: 'Admin/ProductMaster/Edit/:id', loadComponent: () => import('../../components/product-master/create/create.component').then((m) => m.Create_ProductMasterComponent) },

  // { path: 'Admin/ProductMaster/Index', loadComponent: () => import('../../components/product-master/index/index.component').then((m) => m.Index_ProductMasterComponent) },
  { path: 'Admin/StateMaster/Index', loadComponent: () => import('./settings/StateMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/CountryMaster/Index', loadComponent: () => import('./settings/country-master/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/CityMaster/Index', loadComponent: () => import('./settings/CityMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/DesignationMaster/Index', loadComponent: () => import('./settings/DesignationMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/EmployeeTypeMaster/Index', loadComponent: () => import('./settings/EmployeeTypeMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/DepartmentMaster/Index', loadComponent: () => import('./settings/DepartmentMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/DepartmentTypeMaster/Index', loadComponent: () => import('./settings/DepartmentTypeMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/BillCompanyMaster/Index', loadComponent: () => import('./settings/BillCompanyMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/HolidayMaster/Index', loadComponent: () => import('./settings/HolidayMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/CountryMaster/Index', loadComponent: () => import('./settings/country-master/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/RelationshipMaster/Index', loadComponent: () => import('./settings/RelationshipMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/PrefixMaster/Index', loadComponent: () => import('./settings/PrefixMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/RoleMaster/Index', loadComponent: () => import('./settings/RoleMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/RolePerimssionMaster/Index', loadComponent: () => import('./settings/RolePermission/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/RoomTypeMaster/Index', loadComponent: () => import('./settings/RoomTypeMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/ServiceCategoryMaster/Index', loadComponent: () => import('./settings/ServiceCategoryMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/ServiceGroupMaster/Index', loadComponent: () => import('./settings/ServiceGroupMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/FixServiceMaster/Index', loadComponent: () => import('./settings/FixServiceMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/ModuleMaster/Index', loadComponent: () => import('./settings/ModuleMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/TaxSlabMaster/Index', loadComponent: () => import('./settings/TaxSlabMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/RateTypeMaster/Index', loadComponent: () => import('./settings/RateTypeMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/MenuMaster/Index', loadComponent: () => import('./settings/MenuMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/DiscountReasonMaster/Index', loadComponent: () => import('./settings/DiscountReasonMaster/index/index.component').then((m) => m.IndexComponent) },

  { path: 'Admin/RolePerimssion/Index', loadComponent: () => import('./settings/RolePermission/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/ModuleMaster/Index', loadComponent: () => import('./settings/ModuleMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/NumberFormat/Index', loadComponent: () => import('./settings/NumberFormat/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/PlanMaster/Index', loadComponent: () => import('./settings/PlanMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/PlanMaster/Create', loadComponent: () => import('./settings/PlanMaster/create/create.component').then((m) => m.CreateComponent) },
  { path: 'Admin/PlanMaster/Edit/:id', loadComponent: () => import('./settings/PlanMaster/create/create.component').then((m) => m.CreateComponent) },

  { path: 'Admin/ConsultantUnitMaster/Index', loadComponent: () => import('./settings/ConsultantUnitMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/PaymentMode/Index', loadComponent: () => import('./settings/PaymentMode/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/FinYearMaster/Index', loadComponent: () => import('./settings/FinYearMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/WardMaster/Index', loadComponent: () => import('./settings/WardMaster/index/index.component').then((m) => m.IndexComponent) },

  { path: 'Admin/DynamicAmountMaster/Index', loadComponent: () => import('./settings/DynamicAmountMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/MusheerKhalid/Index', loadComponent: () => import('./settings/Musheer Khalid/index/index.component').then((m) => m.IndexComponent) },

  { path: 'Admin/EmployeeRegistration/Index', loadComponent: () => import('./Transactions/EmployeeRegistration/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/EmployeeRegistration/Create', loadComponent: () => import('./Transactions/EmployeeRegistration/create/create.component').then((m) => m.CreateComponent) },
  // { path: 'Admin/ProductMaster/Create', loadComponent: () => import('./../../components/product-master/create/create.component').then((m) => m.Create_ProductMasterComponent) },//========
  { path: 'Admin/EmployeeRegistration/Edit/:id', loadComponent: () => import('./Transactions/EmployeeRegistration/create/create.component').then((m) => m.CreateComponent) },
  { path: 'Admin/ReferredByRegistration/Index', loadComponent: () => import('./Transactions/ReferredByRegistration/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/ConsultantUnitMapping/Index', loadComponent: () => import('./Transactions/ConsultantUnitMapping/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/Kashif/Index', loadComponent: () => import('./settings/Kashif/index/index.component').then((m) => m.IndexComponent) },
  { path: 'Admin/ConsultantUnitMapping/Index', loadComponent: () => import('./Transactions/ConsultantUnitMapping/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/SpecimenMaster/Index', loadComponent: () => import('../LB/Settings/SpecimenMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/AntibioticMaster/Index', loadComponent: () => import('../LB/Settings/AntibioticMater/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/TestMethod/Index', loadComponent: () => import('../LB/Settings/TestMethod/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/TestMethodMapping/Index', loadComponent: () => import('../LB/Settings/TestMethodMapping/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/TestGroupMaster/Index', loadComponent: () => import('../LB/Settings/TestGroupMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/TestGroupMapping/Index', loadComponent: () => import('../LB/Settings/TestGroupMapping/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/OrganismMaster/Index', loadComponent: () => import('../LB/Settings/OrganismMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/OrganismMapping/Index', loadComponent: () => import('../LB/Settings/OrganismMapping/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/ServiceMaster/Index', loadComponent: () => import('../LB/Settings/ServiceMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/ServiceMaster/Create', loadComponent: () => import('../LB/Settings/ServiceMaster/create/create.component').then((m) => m.CreateComponent) },
  { path: 'LB/ServiceMaster/Edit/:id', loadComponent: () => import('../LB/Settings/ServiceMaster/create/create.component').then((m) => m.CreateComponent) },
  { path: 'LB/ReportTemplateMaster/Index', loadComponent: () => import('../LB/Settings/ReportTemplate/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/ReportTemplateMaster/Create', loadComponent: () => import('../LB/Settings/ReportTemplate/create/create.component').then((m) => m.CreateComponent) },
  { path: 'LB/ReportTemplateMaster/Edit/:id', loadComponent: () => import('../LB/Settings/ReportTemplate/create/create.component').then((m) => m.CreateComponent) },
  { path: 'LB/OutSideLabMaster/Index', loadComponent: () => import('../LB/Settings/OutSideLabMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/OutsideTestMapping/Index', loadComponent: () => import('../LB/Settings/OutsideTestMapping/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/OutsideTestMapping/Create', loadComponent: () => import('../LB/Settings/OutsideTestMapping/create/create.component').then((m) => m.CreateComponent) },
  { path: 'LB/TestBooking/Create', loadComponent: () => import('../LB/Transactions/TestBooking/create/create.component').then((m) => m.CreateComponent) },
  { path: 'LB/TestBooking/Index', loadComponent: () => import('../LB/Transactions/TestBooking/index/index.component').then((m) => m.IndexComponent) },
  { path: 'LB/TestBooking/Edit/:id', loadComponent: () => import('../LB/Transactions/TestBooking/create/create.component').then((m) => m.CreateComponent) },
  { path: 'LB/TestBooking/Create', loadComponent: () => import('../LB/Transactions/TestBooking/create/create.component').then((m) => m.CreateComponent) },
  { path: 'LB/ProfileTestMapping/Index', loadComponent: () => import('../LB/Settings/ProfileTestMapping/index/index.component').then((m) => m.IndexComponent) },
  { path: 'RD/ServiceMaster/Index', loadComponent: () => import('../RD/Settings/ServiceMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'RD/ReportTemplateMaster/Index', loadComponent: () => import('../RD/Settings/ReportTemplate/index/index.component').then((m) => m.IndexComponent) },
  { path: 'RD/ReportTemplateMaster/Create', loadComponent: () => import('../RD/Settings/ReportTemplate/create/create.component').then((m) => m.CreateComponent) },
  { path: 'RD/ReportTemplateMaster/Edit/:id', loadComponent: () => import('../RD/Settings/ReportTemplate/create/create.component').then((m) => m.CreateComponent) },
  { path: 'Admin/PrefixMaster/Index', loadComponent: () => import('./settings/PrefixMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'HR/LoanTypeMaster/Index', loadComponent: () => import('../HR/Settings/LoanTypeMaster/index/index.component').then((m) => m.IndexComponent) },
  { path: 'HR/EmployeeLoan/Index', loadComponent: () => import('../HR/Transactions/EmployeeLoan/index/index.component').then((m) => m.IndexComponent) },
  { path: 'HR/EmployeeLoan/Create', loadComponent: () => import('../HR/Transactions/EmployeeLoan/create/create.component').then((m) => m.CreateComponent) },
  { path: 'HR/EmployeeLoan/Edit/:id', loadComponent: () => import('../HR/Transactions/EmployeeLoan/create/create.component').then((m) => m.CreateComponent) },
  { path: 'HR/rptEmployeeRegister/Index', loadComponent: () => import('../HR/Reports/rptEmployeeRegister/index/index.component').then((m) => m.IndexComponent) },
];
